### ISSUE TITLE
MVP Checklist

### ISSUE THREAD

**Issue by brookeangel** [AviWaiz/Shutter#1]
You can remove these lines from the main checklist

> Adequate seed data to demonstrate the site's features
>  features for creating a photo portfolio, editing photos etc...
> CSS styling that is aesthetic

since each sub-feature contains these two categories. 

Also make sure to separate the links 

```
View Wireframes
React Components
Flux Cycles
API endpoints
DB schema
```

from your mvp checklist!

**Comment by AviWaiz** [comment]
fixed
